packages:
    - "electron"

allowBuilds:
    electron: true
    electron-winstaller: true
minimumReleaseAge: 2440
minimumReleaseAgeExclude:
    - vite

onlyBuiltDependencies:
    - "@tailwindcss/oxide"
    - esbuild

patchedDependencies:
    bits-ui@2.18.1: patches/bits-ui@2.18.1.patch
